# -*- coding: utf-8 -*-
"""Machine_learning_skill.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZdViWoKYY_iI1Fs1OBufeJ4O4JQfLia
"""

x = 5
y = 3.14
name = "CGPA"
is_placed = True

print(x, type(x))
print(y, type(y))
print(name, type(name))
print(is_placed, type(is_placed))

# --- ARTHEMATIC OPERATIONS ---
a = 7
b = 2
print("a+b=",a+b)
print("a-b=",a-b)
print("a*b=",a*b)
print("a/b=",a/b)
print("a%b=",a%b)
print("a//b=",a//b)
print("a**2=",a**2)

cgpa = 8.4
print("cgpa == 8.4 :", cgpa == 8.4)
print("cgpa > 8 :", cgpa > 8)
print("cgpa < 6 :", cgpa < 6)

model_name = "Logistic Regression"
accuracy = 0.87345
print("Accuracy of " + model_name + " is "+str(accuracy))
print(f"Accuracy of {model_name} is {accuracy}")
print(f"Accuracy of {model_name} is {accuracy:.3f}")

# --- STRINGS & F-STRINGS ---

model_name = "Logistic Regression"
accuracy = 0.87345

# Old, clunky way (avoid this):
print("Accuracy of " + model_name + " is " + str(accuracy))

# f-string way (use this):
print(f"Accuracy of {model_name} is {accuracy}")

# ':.3f' inside the braces rounds a float to 3 decimal places -
# you will use this in almost every experiment to print clean metrics.
print(f"Accuracy of {model_name} is {accuracy:.3f}")

# --- LISTS & INDEXING ---

features = ["CGPA", "AptitudeTestScore", "CodingTestScore", "MockInterviewScore"]

print(features)          # the whole list
print(features[0])       # FIRST item - Python counts from 0, not 1
print(features[1])       # SECOND item
print(features[-1])      # LAST item - negative index counts from the end
print(len(features))     # how many items are in the list

# Slicing: features[start:end] gives you a sub-list (end is NOT included)
print(features[0:2])     # first two items

# Adding to a list
features.append("Internships")
print(features)

# --- DICTIONARIES ---

# key = model name (string), value = the actual model object
from sklearn.linear_model import Ridge, Lasso, ElasticNet

models = {
    "Ridge": Ridge(alpha=1.0),
    "Lasso": Lasso(alpha=0.01),
    "ElasticNet": ElasticNet(alpha=0.01),
}

print(models)                  # the whole dictionary
print(models["Ridge"])         # access one value by its key

# Looping over a dictionary's keys and values together:
for name, model in models.items():
    print(f"Model name: {name}  ->  Object: {model}")

# --- IF / ELIF / ELSE ---

cgpa = 8.2

if cgpa >= 9:
    tier = "High"
elif cgpa >= 7:
    tier = "Mid"
else:
    tier = "Low"

print(f"CGPA {cgpa} falls into tier: {tier}")

# You can also use if/else to guard against bad data,
# e.g. before dividing or indexing:
missing_count = 0
if missing_count == 0:
    print("No missing values - safe to proceed.")
else:
    print("Missing values found - impute before modelling.")

# --- FOR LOOPS ---

depths = [2, 4, 6, 8, 10]

for depth in depths:
    print(f"Training a tree with max_depth = {depth}")

# range() generates a sequence of numbers without writing them all out
for epoch in range(5):          # 0, 1, 2, 3, 4
    print(f"Epoch {epoch}: computing gradient...")

# Looping with an index AND a value using enumerate()
for i, d in enumerate(depths):
    print(f"Sweep step {i}: depth={d}")

# --- FUNCTIONS ---

def classify_cgpa(cgpa):
    """Takes a CGPA value and returns a tier label."""
    if cgpa >= 9:
        return "High"
    elif cgpa >= 7:
        return "Mid"
    else:
        return "Low"

# Calling the function with different inputs:
print(classify_cgpa(9.5))
print(classify_cgpa(7.8))
print(classify_cgpa(5.2))

# A function with more than one input (parameter):
def describe_model(name, accuracy):
    return f"{name} achieved {accuracy:.1%} accuracy"

print(describe_model("Random Forest", 0.913))

# --- IMPORTING LIBRARIES ---

import pandas as pd                          # gives pandas the short name "pd"
import numpy as np                           # gives numpy the short name "np"
from sklearn.linear_model import LogisticRegression   # import ONE class from a big library
from sklearn.metrics import accuracy_score

# Colab-only: install a library that isn't there by default (note the leading !)
# !pip install xgboost

print("pandas version:", pd.__version__)
print("numpy version :", np.__version__)

# 9. IMPORTING LIBRARIES
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 1. VARIABLES & TYPES
csv_path = "placement_predict_50k_Dataset.csv"     # a string
min_acceptable_accuracy = 0.7                        # a float

# 4. LISTS
features = ["CGPA", "AptitudeTestScore", "CodingTestScore", "AttendancePercent"]

df = pd.read_csv(csv_path)
df[features] = df[features].fillna(df[features].median())   # handle missing values
X, y = df[features], df["PlacementStatus"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# 5. DICTIONARIES - comparing two models by name
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(max_depth=5, random_state=42),
}

# 8. FUNCTION definition
def evaluate_model(model, X_train, y_train, X_test, y_test):
    """Fits a model and returns its test accuracy."""
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    return accuracy_score(y_test, preds)

# 7. FOR LOOP over the dictionary + 6. IF/ELIF/ELSE + 3. F-STRINGS
for name, model in models.items():
    acc = evaluate_model(model, X_train, y_train, X_test, y_test)   # 2. uses arithmetic internally

    if acc >= min_acceptable_accuracy:
        verdict = "GOOD"
    else:
        verdict = "NEEDS WORK"

    print(f"{name:<20} accuracy={acc:.3f}  -> {verdict}")